openapi: 3.1.0
x-stoplight:
  id: 7tzug65yrskue
info:
  title: videos
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/videos/{videoId}':
    parameters:
      - schema:
          type: integer
        name: videoId
        in: path
        required: true
        description: Id of an existing video.
    get:
      summary: Get Video Info by Video ID
      tags: []
      responses:
        '200':
          description: Video Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              examples:
                Get Video Alice Smith:
                  value:
                    id: 142
                    name: Alice
                    url: http://bitu.vg/hablobiw
                    thumbnailUrl: https://images.unsplash.com/photo-1649358787769-8a380f337497?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=128&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1MjAwNjQzNg&ixlib=rb-1.2.1&q=80&w=128
                    timesViewed: 42
                    isPrivate: true
        '404':
          description: Video Not Found
      operationId: get-videos-videoId
      description: Retrieve the information of the video with the matching video ID.
    put:
      summary: Update Video Information
      operationId: put-videos-videoId
      responses:
        '200':
          description: Video Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              examples:
                Updated Video Rebecca Baker:
                  value:
                    name: Rebecca
                    url: http://bitu.vg/hablobiw
                    thumbnailUrl: https://images.unsplash.com/photo-1649358787769-8a380f337497?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=128&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1MjAwNjQzNg&ixlib=rb-1.2.1&q=80&w=128
                    timesViewed: 42
                    isPrivate: false
        '404':
          description: Video Not Found
      description: Update the information of an existing video.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                thumbnailUrl:
                  type: string
                timesViewed:
                  type: integer
            examples:
              Update Name:
                value:
                  name: Rebecca
              Update ThumbnailUrl:
                value:
                  thumbnailUrl: https://images.unsplash.com/photo-1649358787769-8a380f337497?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=128&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1MjAwNjQzNg&ixlib=rb-1.2.1&q=80&w=128
        description: Patch video properties to update.
    delete:
      summary: 'Delete video'
      operationId: delete-videos-videoId
      responses:
        '200':
          description: OK
      description: Delete an existing video.
  /videos:
    post:
      summary: Create New Video
      operationId: post-video
      responses:
        '200':
          description: Video Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video'
              examples:
                New Video Bob Fellow:
                  value:
                    id: 12
                    name: Bob
                    url: http://bitu.vg/hablobiw
                    thumbnailUrl: https://images.unsplash.com/photo-1649358787769-8a380f337497?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=128&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1MjAwNjQzNg&ixlib=rb-1.2.1&q=80&w=128
                    timesViewed: 42
                    isPrivate: false
        '400':
          description: Missing Required Information
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                url:
                  type: string
                thumbnailUrl:
                  type: string
                timesViewed:
                  type: integer
              required:
                - name
                - url
                - thumbnailUrl
                - timesViewed
            examples:
              Create Video Bob Fellow:
                value:
                  name: Bob
                  url: http://bitu.vg/hablobiw
                  thumbnailUrl: https://images.unsplash.com/photo-1649358787769-8a380f337497?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=128&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1MjAwNjQzNg&ixlib=rb-1.2.1&q=80&w=128
                  timesViewed: 42
        description: Post the necessary fields for the API to create a new video.
      description: Create a new video.
    parameters: []
components:
  schemas:
    Video:
      title: Video
      type: object
      description: ''
      examples:
        - id: 142
          name: Alice
          url: http://bitu.vg/hablobiw
          thumbnailUrl: https://images.unsplash.com/photo-1649358787769-8a380f337497?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&h=128&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY1MjAwNjQzNg&ixlib=rb-1.2.1&q=80&w=128
          timesViewed: 42
          isPrivate: true
      properties:
        id:
          type: integer
          description: Unique identifier for the given video.
        name:
          type: string
        url:
          type: string
        thumbnailUrl:
          type: string
          format: thumbnailUrl
        timesViewed:
          type: integer
        isPrivate:
          type: boolean
          description: Set to true if the video's email has been verified.
      required:
        - id
        - name
        - url
        - thumbnailUrl
        - isPrivate

